import { mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { resolve } from 'node:path';
import { pathToFileURL } from 'node:url';
import { createHash } from 'node:crypto';
import { version } from '../package.json';

// Package only the host binary: a successful cross-compile would not establish
// that another architecture works. Public release URLs belong to the release job.
if (!['darwin', 'linux'].includes(process.platform)) throw new Error('Packaging supports macOS and Linux.');
const arch = process.arch === 'x64' ? 'x86_64' : process.arch;
const artifact = `pacifico-${process.platform}-${arch}.tar.gz`;
mkdirSync('dist/local-tap/Formula', { recursive: true });
const tar = Bun.spawnSync([
  'tar',
  '-czf',
  `dist/${artifact}`,
  '-C',
  'dist',
  'pacifico',
  '-C',
  '..',
  'LICENSE',
  'NOTICE',
]);
if (tar.exitCode !== 0) throw new Error(new TextDecoder().decode(tar.stderr));
const sha = createHash('sha256')
  .update(readFileSync(`dist/${artifact}`))
  .digest('hex');
const uri = pathToFileURL(resolve(`dist/${artifact}`)).href;
const formula = `# Generated by bun run package:local. Local artifact; not a published release.
class Pacifico < Formula
  desc "Local archive and recall for AI coding sessions"
  homepage "https://github.com/emersoftware/pacifico"
  url "${uri}"
  version "${version}"
  sha256 "${sha}"
  license "MIT"
  depends_on :${process.platform === 'darwin' ? 'macos' : 'linux'}
  depends_on arch: :${process.arch === 'arm64' ? 'arm64' : 'x86_64'}

  def install
    bin.install "pacifico"
  end

  test do
    assert_match "pacifico ${version}", shell_output("#{bin}/pacifico --version")
  end
end
`;
writeFileSync('dist/local-tap/Formula/pacifico.rb', formula);
writeFileSync(`dist/${artifact}.sha256`, `${sha}  ${artifact}\n`);
process.stdout.write(`Packaged ${artifact}\nSHA256 ${sha}\nLocal formula: dist/local-tap/Formula/pacifico.rb\n`);
